version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: postgres
    ports:
      - '5432:5432'

  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizz-app
    ports:
      - '3000:3000'
    depends_on: 
      - db
