version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    ports:
      - '${DB_PORT}:5432'

  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizz-app
    ports:
      - '3000:3000'
    depends_on: 
      - db
